"""Labwire core protocol library: server and client SDKs.

Wrap any device in the protocol with :class:`Instrument` and
:class:`InstrumentServer`; drive any instrument with :class:`LabwireClient`.

Example:
    >>> from labwire.core import PROTOCOL_VERSION
    >>> PROTOCOL_VERSION
    '0.2'
"""

from labwire.core._meta import PROTOCOL_VERSION, __version__
from labwire.core.capabilities import (
    CONFIRMATION_REQUIRED_CLASSES,
    KIND_REGISTRY,
    ChannelSpec,
    CommandSpec,
    IdentityInfo,
    InstrumentDescriptor,
    InterlockSpec,
    ResourceSpec,
    SafetyClass,
    valid_kind,
)
from labwire.core.client import (
    CommandHandle,
    EventStream,
    LabwireClient,
    TelemetrySample,
    TelemetrySubscription,
)
from labwire.core.errors import (
    AuthorizationRequiredError,
    BusyError,
    CanceledError,
    ConfirmationRequiredError,
    DeviceTimeoutError,
    HardwareFaultError,
    InterlockError,
    InternalError,
    InvalidParamsError,
    InvalidRequestError,
    LabwireError,
    MethodNotFoundError,
    NotCancelableError,
    StaleRevisionError,
    UnknownReferenceError,
    UnsupportedError,
    ValidationError,
    error_from_wire,
)
from labwire.core.grants import Grant, GrantStore, GrantVerdict
from labwire.core.jcs import jcs_canonical, jcs_dumps, params_digest
from labwire.core.messages import (
    MESSAGE_TYPES,
    Authorization,
    CommandState,
    CommandStatus,
    EventNotification,
    EventSeverity,
    PeerInfo,
    Progress,
    ResourceChangedData,
    ResourceIndexEntry,
    ResourceReadResult,
    ResourceRevision,
    ServerCapabilities,
)
from labwire.core.server import (
    Clock,
    CommandContext,
    Instrument,
    InstrumentResource,
    InstrumentServer,
    Interlock,
    ResourceRef,
    ResourceSnapshot,
    RunRecord,
    SystemClock,
    TelemetryChannel,
    channel,
    command,
    interlock,
    resource,
    unit_field,
)
from labwire.core.session import JsonRpcSession, SessionClosed
from labwire.core.signing import (
    MANIFEST_VERSION,
    Manifest,
    SigningKey,
    VerificationResult,
    sign_manifest,
    verify_bundle,
    verify_manifest,
)
from labwire.core.transport import MemoryTransport, Transport, TransportClosed, WebSocketTransport

__all__ = [
    "CONFIRMATION_REQUIRED_CLASSES",
    "KIND_REGISTRY",
    "MANIFEST_VERSION",
    "MESSAGE_TYPES",
    "PROTOCOL_VERSION",
    "Authorization",
    "AuthorizationRequiredError",
    "BusyError",
    "CanceledError",
    "ChannelSpec",
    "Clock",
    "CommandContext",
    "CommandHandle",
    "CommandSpec",
    "CommandState",
    "CommandStatus",
    "ConfirmationRequiredError",
    "DeviceTimeoutError",
    "EventNotification",
    "EventSeverity",
    "EventStream",
    "Grant",
    "GrantStore",
    "GrantVerdict",
    "HardwareFaultError",
    "IdentityInfo",
    "Instrument",
    "InstrumentDescriptor",
    "InstrumentResource",
    "InstrumentServer",
    "Interlock",
    "InterlockError",
    "InterlockSpec",
    "InternalError",
    "InvalidParamsError",
    "InvalidRequestError",
    "JsonRpcSession",
    "LabwireClient",
    "LabwireError",
    "Manifest",
    "MemoryTransport",
    "MethodNotFoundError",
    "NotCancelableError",
    "PeerInfo",
    "Progress",
    "ResourceChangedData",
    "ResourceIndexEntry",
    "ResourceReadResult",
    "ResourceRef",
    "ResourceRevision",
    "ResourceSnapshot",
    "ResourceSpec",
    "RunRecord",
    "SafetyClass",
    "ServerCapabilities",
    "SessionClosed",
    "SigningKey",
    "StaleRevisionError",
    "SystemClock",
    "TelemetryChannel",
    "TelemetrySample",
    "TelemetrySubscription",
    "Transport",
    "TransportClosed",
    "UnknownReferenceError",
    "UnsupportedError",
    "ValidationError",
    "VerificationResult",
    "WebSocketTransport",
    "__version__",
    "channel",
    "command",
    "error_from_wire",
    "interlock",
    "jcs_canonical",
    "jcs_dumps",
    "params_digest",
    "resource",
    "sign_manifest",
    "unit_field",
    "valid_kind",
    "verify_bundle",
    "verify_manifest",
]
