"""``labwire probe``: ask a SCPI endpoint who it is, draft its annotation.

The draft is a starting point, not a capability claim: every field the
probe cannot learn from ``*IDN?`` is a TODO, and the header says so. The
honest status of the whole transport stack is in docs/HARDWARE.md: real
transports, tested against simulators, awaiting hardware.
"""

import asyncio
import re

from labwire.drivers import LineProtocolClient

_IDN_FIELDS = ("manufacturer", "model", "serial_number", "firmware_version")


def parse_idn(reply: str) -> dict[str, str]:
    """Split a ``*IDN?`` reply into its conventional four fields.

    Example:
        >>> parse_idn("ACME,PSU-1,SN1,1.0")["model"]
        'PSU-1'
    """
    parts = [part.strip() for part in reply.split(",")]
    return {
        field: (parts[index] if index < len(parts) and parts[index] else "TODO")
        for index, field in enumerate(_IDN_FIELDS)
    }


def slug(model: str) -> str:
    """A filesystem-safe name for the draft file."""
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", model).strip("-")
    return cleaned or "instrument"


async def probe_endpoint(link: LineProtocolClient) -> dict[str, str]:
    """Open the link, ask ``*IDN?``, close, return the parsed identity."""
    await link.open()
    try:
        reply = await link.command("*IDN?")
    finally:
        await link.close()
    return parse_idn(reply)


def draft_annotation(identity: dict[str, str], endpoint_lines: list[str]) -> str:
    """The draft annotation file for one probed endpoint."""
    lines = [
        "# Draft instrument annotation, generated by `labwire probe`.",
        "# Nothing about this device is verified beyond the *IDN? reply",
        "# recorded below. Resolve every TODO against the instrument manual",
        "# before serving it; docs/HARDWARE.md walks through the process.",
        "version: 1",
        "identity:",
        *(f"  {field}: {identity[field]!r}" for field in _IDN_FIELDS),
        "endpoint:",
        *(f"  {line}" for line in endpoint_lines),
        "driver: TODO  # a labwire.drivers class ONLY if the manual's command",
        "              # set matches it; no labwire driver claims",
        "              # compatibility with any physical instrument model",
        "annotations:",
        "  units: TODO   # UCUM code for every quantity, from the manual",
        "  ranges: TODO  # safe operating ranges, from the manual",
        "  safety: TODO  # which operations are irreversible (S2) or hazardous (S3)",
        "",
    ]
    return "\n".join(lines)


def run_probe(
    target: str | None, serial_device: str | None, baud: int
) -> tuple[dict[str, str], list[str]]:
    """Resolve the CLI arguments into a probed identity + endpoint lines."""
    if (target is None) == (serial_device is None):
        raise ValueError("give exactly one endpoint: HOST:PORT, or --serial DEVICE")
    if target is not None:
        host, _, port = target.rpartition(":")
        if not host or not port.isdigit():
            raise ValueError(f"{target!r} is not HOST:PORT")
        link = LineProtocolClient(host, int(port))
        endpoint_lines = ["transport: tcp", f"address: {target!r}"]
    else:
        assert serial_device is not None
        link = LineProtocolClient.serial(serial_device, baudrate=baud)
        endpoint_lines = ["transport: serial", f"device: {serial_device!r}", f"baud: {baud}"]
    identity = asyncio.run(probe_endpoint(link))
    return identity, endpoint_lines
